# Site settings
title: OutCage
header-img: img/home-bg.jpg
email: yang_shuai_ooo@yeah.net
copyright_name: OutCage
description: "记录一个菜鸟的学习步伐，如果能帮助到人就太好了。"
baseurl: ""
url: "http://lucksevenl7.github.io"
github_username:  lucksevenl7
email_username:  yang_shuai_ooo
# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
